DATA_PATH: 'C:\coding\data\tk_day_manager'
TIMEZONE_STR: 'Europe/Berlin'

KCAL_TARGET: 2500
CARB_RATIO: 0.4
FAT_RATIO: 0.3
PROTEIN_RATIO: 0.3
WATER_TARGET: 3000

EXERCISE_MINUTES_TARGET: 45

POMODORO_MINUTES_TARGET: 360

GET_UP_HOUR: 7
SLEEP_DURATION_HOURS: 7

SEQUENCE_HABITS:
  'Only slept in bed': 1
  'Woke up on time': 2
  'Glass of water': 1
  'Morning exercise': 1
  'Breakfast': 1
  'Made todo list': 1
  'Multivitamin': 1
  'Flat is clean': 1

HABITS:
  '<200mg Caffeine': 1
  'Protein shake': 1
  'No soft drinks': 1

TIMED_MESSAGES:
  'good morning. please make a plan for the day': 0.5
  'drink last coffee now.': -6.5
  'no more coffee for today.': -6
  'eat last food now.': -4
  'no more food for today.': -3
  'three hours left.': -3
  'two hours left.': -2
  'one hour left.': -1
  'starting in 15 minutes, dim the lights and read for 20 minutes. go to the bathroom now': -0.4833333333
  'dim the lights now and read a book for 20 minutes before goind to bed.': -0.333333333
  'go to bed now.': -0.01
N_WAKE_DAY_SECTION_MESSAGES: 100

POMODORO_TIMER_MINUTE_OPTIONS:
  - 5,
  - 10
  - 15
  - 20
  - 25
  - 30
  - 45
  - 60
  - 90
  - 120

SCORE_HALF_LIFE: 7
